name: Deploy Drawing App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v2

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask app (development server)
        run: |
          export FLASK_APP=app.py
          export FLASK_ENV=development
          python app.py  # Run Flask app using the built-in server
